# Generated by Django 5.2.6 on 2025-10-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_draft',
            new_name='save_as_draft',
        ),
    ]
