# Generated by Django 5.2.6 on 2025-10-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_is_draft_post_save_as_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save_as_draft',
            new_name='is_draft',
        ),
    ]
