# Generated by Django 5.2.6 on 2025-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_save_as_draft_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Save as Draft'),
        ),
    ]
