# Generated by Django 5.2.7 on 2025-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20251029_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='oktogo', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
